<a href="https://colab.research.google.com/github/kyoseikamada/machinelearning/blob/main/neural-network1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ライブラリのimport

In [1]:
import numpy as np

# NumPy 基本まとめ

##1. 配列の作成

In [2]:
# 1次元配列（ベクトル）
a = np.array([1, 2, 3])
print("a:", a)

a: [1 2 3]


In [3]:
# 2次元配列（行列）
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("b:\n", b)

b:
 [[1 2 3]
 [4 5 6]]


In [4]:
# 指定サイズで初期化
zeros = np.zeros((2, 3))   # 2行3列、すべて0
ones = np.ones((2, 3))     # 2行3列、すべて1
print("zeros:\n", zeros)
print("ones:\n", ones)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# 連続値の生成
ar = np.arange(0, 10, 2)   # 0〜10未満、2刻み
ls = np.linspace(0, 1, 5)  # 0〜1を5分割
print("arange:", ar)
print("linspace:", ls)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 2. shape と dtype

In [6]:
# shape = (行, 列)
print("b.shape:", b.shape)

# dtype = データ型
print("b.dtype:", b.dtype)

b.shape: (2, 3)
b.dtype: int64


## 3. インデックス / スライス


In [7]:
# 要素アクセス（行, 列）
print("b[0,1]:", b[0, 1])  # 1行目2列目

# 行の取得
print("b[0]:", b[0])       # 1行目

# 列の取得
print("b[:,1]:", b[:, 1])  # 2列目

# 部分行列（スライス）
print("b[0:2,1:3]:\n", b[0:2, 1:3])


b[0,1]: 2
b[0]: [1 2 3]
b[:,1]: [2 5]
b[0:2,1:3]:
 [[2 3]
 [5 6]]


## 4. 要素ごとの演算（超重要）

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 同じshape同士は要素ごとに計算される
print("x + y:", x + y)
print("x * y:", x * y)
print("x ** 2:", x ** 2)


x + y: [5 7 9]
x * y: [ 4 10 18]
x ** 2: [1 4 9]


## 5. ブロードキャスト（超重要）

In [9]:

# (2,3) + (3,) の計算
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# xが各行に自動で拡張される
print("m + x:\n", m + x)

m + x:
 [[2 4 6]
 [5 7 9]]


## 6. 行列演算（要素演算と違う）

In [10]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 要素ごとの掛け算
print("A * B:\n", A * B)

# 行列積（線形代数）
print("A @ B:\n", A @ B)

A * B:
 [[ 5 12]
 [21 32]]
A @ B:
 [[19 22]
 [43 50]]


## 7. 統計処理

In [11]:
data = np.array([1, 2, 3, 4, 5])

print("sum:", np.sum(data))
print("mean:", np.mean(data))
print("max:", np.max(data))
print("min:", np.min(data))

sum: 15
mean: 3.0
max: 5
min: 1



##8. reshape（形の変更）


In [12]:
r = np.arange(6)
print("before:", r)

# (6,) → (2,3)
r2 = r.reshape(2, 3)
print("after:\n", r2)

before: [0 1 2 3 4 5]
after:
 [[0 1 2]
 [3 4 5]]


## 9. 条件抽出（フィルタ）


In [13]:
a = np.array([1, 2, 3, 4, 5])

# 条件（True/False配列）
mask = a > 3
print("mask:", mask)

# 条件に合う要素だけ取り出す
print("filtered:", a[mask])

mask: [False False False  True  True]
filtered: [4 5]


## 10. グラフ・機械学習でよく使う形

In [14]:

# 入力データ生成
x = np.linspace(-5, 5, 100)

# 関数適用（ベクトル化）
y = x ** 2

print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (100,)
y shape: (100,)


#勾配を求める

In [15]:
def numerical_gradient(f, x):
  """
  Parameters
  ----------
  f : function
      入力: numpy配列
      出力: numpy配列
  x : numpy.ndarray
  """
  h = 1e-4
  grad = np.zeros_like(x)

  for idx in range(x.size):
    tmp_val = x[idx]
    # f(x+h)の計算
    x[idx] = tmp_val + h
    fxh1 = f(x)

    # f(x-h)の計算
    x[idx] = tmp_val - h
    fxh2 = f(x)

    grad[idx] = (fxh1 - fxh2) / (2*h)
    x[idx] = tmp_val

  return grad


In [16]:
def func(x):
  """
  2次元配列(numpy配列)
  """
  return x[0]**2 + x[1]**2

print("例1:", numerical_gradient(func, np.array([3.0, 4.0])))
print("例2:", numerical_gradient(func, np.array([0.0, 2.0])))
print("例3:", numerical_gradient(func, np.array([3.0, 0.0])))

例1: [6. 8.]
例2: [0. 4.]
例3: [6. 0.]


#勾配降下法

In [17]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
  """
  f: function
  init_x: xの初期値
  lr: 学習率
  step_num: 学習回数
  """
  x = init_x

  for i in range(step_num):
    grad = numerical_gradient(f, x)
    x -= lr * grad

  return x

##例）関数の極小値を求める

In [18]:
init_x = np.array([-3.0, 4.0])
x = gradient_descent(func, init_x, lr=0.1, step_num=100)

print(x)

[-6.11110793e-10  8.14814391e-10]


In [19]:
func(x)

np.float64(1.0373788922158197e-18)

funcの極小値は0なので、ほぼ正解に近い値を求められている

ハイパーパラメータの学習率lrを小さい値に設定すると上手くいかない

In [20]:
init_x = np.array([-3.0, 4.0])
x = gradient_descent(func, init_x, lr=0.001, step_num=100)

print("x:", x)
print("func:", func(x))

x: [-2.45570041  3.27426722]
func: 16.75129034343203


#ソフトマックス関数・クロスエントロピー関数

## ソフトマックス関数

$$
\mathrm{softmax}(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{n} e^{x_j}}
$$

数値安定化のための実装では、以下を用いる：

$$
\mathrm{softmax}(x_i) = \frac{e^{x_i - \max(x)}}{\sum_{j=1}^{n} e^{x_j - \max(x)}}
$$



In [21]:
import numpy as np

def softmax(x):
    """
    x: numpy.ndarray (n,) または (batch, n)
    return: softmax適用結果（同じshape）
    """
    # 数値安定化（オーバーフロー防止）
    x = x - np.max(x, axis=-1, keepdims=True)

    exp_x = np.exp(x)
    sum_exp = np.sum(exp_x, axis=-1, keepdims=True)

    return exp_x / sum_exp

## クロスエントロピー損失関数

分類問題におけるクロスエントロピー：

$$
L = - \sum_{i=1}^{n} y_i \log p_i
$$

ここで：

- $y_i$：正解ラベル（one-hotベクトル）
- $p_i$：予測確率（softmaxの出力）

---

バッチデータの場合：

$$
L = - \frac{1}{N} \sum_{k=1}^{N} \sum_{i=1}^{n} y_{k,i} \log p_{k,i}
$$

In [22]:
import numpy as np

def cross_entropy(y_true, y_pred):
    """
    y_true: (n,) または (batch, n) one-hot
    y_pred: (n,) または (batch, n) softmax出力

    return: スカラー損失
    """
    # log(0)防止
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)

    return -np.sum(y_true * np.log(y_pred)) / y_true.shape[0]

## softmax + クロスエントロピーの勾配

softmax：
$$
p_i = \frac{e^{z_i}}{\sum_j e^{z_j}}
$$

クロスエントロピー：
$$
L = - \sum_i y_i \log p_i
$$

このとき、入力 $z$ に対する勾配は：

$$
\frac{\partial L}{\partial z_i} = p_i - y_i
$$

## softmax + クロスエントロピーの勾配導出

## 前提

softmax：
$$
p_i = \frac{e^{z_i}}{\sum_k e^{z_k}}
$$

クロスエントロピー：
$$
L = -\sum_i y_i \log p_i
$$

---

## ステップ①：logを展開

$$
\log p_i = \log \left( \frac{e^{z_i}}{\sum_k e^{z_k}} \right)
= z_i - \log \left( \sum_k e^{z_k} \right)
$$

これを損失関数に代入：

$$
L = -\sum_i y_i \left( z_i - \log \sum_k e^{z_k} \right)
$$

展開すると：

$$
L = -\sum_i y_i z_i + \sum_i y_i \log \sum_k e^{z_k}
$$

---

## ステップ②：one-hotの性質

one-hotベクトルでは：

$$
\sum_i y_i = 1
$$

したがって：

$$
\sum_i y_i \log \sum_k e^{z_k}
= \log \sum_k e^{z_k}
$$

よって：

$$
L = -\sum_i y_i z_i + \log \sum_k e^{z_k}
$$

---

## ステップ③：微分

### 第1項

$$
\frac{\partial}{\partial z_j} \left( -\sum_i y_i z_i \right)
= -y_j
$$

---

### 第2項

$$
\frac{\partial}{\partial z_j} \log \sum_k e^{z_k}
= \frac{1}{\sum_k e^{z_k}} \cdot e^{z_j}
$$

$$
= \frac{e^{z_j}}{\sum_k e^{z_k}} = p_j
$$

---

## ステップ④：まとめ

$$
\frac{\partial L}{\partial z_j}
= -y_j + p_j
$$

---

## 結論

$$
\frac{\partial L}{\partial z} = p - y
$$

---

## ポイント

- logを先に展開すると計算が簡単になる
- one-hotの性質で式が大きく簡約される
- 結果は非常にシンプルな形になる

---

## 直感的理解

- 勾配 = 予測 - 正解
- 予測が大きすぎる → 減らす
- 小さすぎる → 増やす

# 1層ニューラルネットの勾配導出（W, b）

## モデル

入力：
$$
x \in \mathbb{R}^d
$$

重み・バイアス：
$$
W \in \mathbb{R}^{d \times n}, \quad b \in \mathbb{R}^n
$$

線形変換：
$$
z = xW + b
$$

softmax：
$$
p = \mathrm{softmax}(z)
$$

損失関数（クロスエントロピー）：
$$
L = -\sum_i y_i \log p_i
$$

---

## 既知の結果（重要）

$$
\frac{\partial L}{\partial z} = p - y
$$

---

## ステップ①：bの勾配

$$
z = xW + b
$$

なので：

$$
\frac{\partial z}{\partial b} = I
$$

よって：

$$
\frac{\partial L}{\partial b}
= \frac{\partial L}{\partial z}
= p - y
$$

---

## ステップ②：Wの勾配

$$
z = xW + b
$$

各成分：
$$
z_j = \sum_i x_i W_{i,j} + b_j
$$

---

### 微分

$$
\frac{\partial z_j}{\partial W_{i,j}} = x_i
$$

---

### 連鎖律

$$
\frac{\partial L}{\partial W_{i,j}}
= \frac{\partial L}{\partial z_j} \cdot \frac{\partial z_j}{\partial W_{i,j}}
$$

$$
= (p_j - y_j) \cdot x_i
$$

---

## 行列形式

$$
\frac{\partial L}{\partial W} = x^T (p - y)
$$

---

## まとめ

$$
\frac{\partial L}{\partial z} = p - y
$$

$$
\frac{\partial L}{\partial b} = p - y
$$

$$
\frac{\partial L}{\partial W} = x^T (p - y)
$$

---

## バッチ版

入力：
$$
X \in \mathbb{R}^{N \times d}
$$

$$
Z = XW + b
$$

$$
P = \mathrm{softmax}(Z)
$$

---

勾配：

$$
\frac{\partial L}{\partial Z} = P - Y
$$

$$
\frac{\partial L}{\partial b} = \sum_{k=1}^{N} (P - Y)
$$

$$
\frac{\partial L}{\partial W} = X^T (P - Y)
$$

---

## 直感

- 勾配 = 誤差（p - y）
- Wの勾配 = 入力 × 誤差
- bの勾配 = 誤差そのもの

---

## ポイント

- 非常にシンプルな形になる
- バックプロパゲーションの基本構造
- すべての層で同じパターンが繰り返される

## パラメータ更新（勾配降下法）

$$
W := W - \eta \frac{\partial L}{\partial W}
$$

$$
b := b - \eta \frac{\partial L}{\partial b}
$$

ここで：

- $\eta$：学習率（learning rate）

##コード例

In [29]:
import numpy as np

def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

def gradients(x, W, b, y_true):
    """
    x: (d,)
    W: (d, n)
    b: (n,)
    y_true: (n,) one-hot
    """
    z = x @ W + b
    p = softmax(z)

    dz = p - y_true  # (n,)

    dW = np.outer(x, dz)  # (d, n)
    db = dz

    return dW, db

In [30]:
import numpy as np

def softmax(x):
    x = x - np.max(x)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

# 初期化
x = np.array([1.0, 2.0])      # 入力
y = np.array([1, 0])          # 正解

W = np.random.randn(2, 2)
b = np.zeros(2)

lr = 0.1

# --- forward ---
z = x @ W + b
p = softmax(z)

# --- backward ---
dz = p - y
dW = np.outer(x, dz)
db = dz

# --- update ---
W -= lr * dW
b -= lr * db

print("p:", p)
print("updated W:\n", W)

p: [0.03401119 0.96598881]
updated W:
 [[ 0.17410709  0.91478314]
 [-1.89331467 -1.07341573]]


# 2層ニューラルネットの勾配導出（直感＋数式）

## モデル構造

入力：
$$
x \in \mathbb{R}^d
$$

第1層（隠れ層）：
$$
z^{(1)} = x W^{(1)} + b^{(1)}
$$

活性化関数（ReLU）：
$$
h = \mathrm{ReLU}(z^{(1)})
$$

第2層（出力層）：
$$
z^{(2)} = h W^{(2)} + b^{(2)}
$$

softmax：
$$
p = \mathrm{softmax}(z^{(2)})
$$

損失関数：
$$
L = -\sum_i y_i \log p_i
$$

---

## 全体の流れ（図イメージ）

$$
x \rightarrow z^{(1)} \rightarrow h \rightarrow z^{(2)} \rightarrow p \rightarrow L
$$

---

## ステップ①：出力層の勾配

既知の結果：

$$
\frac{\partial L}{\partial z^{(2)}} = p - y
$$

---

## ステップ②：第2層の勾配

$$
\frac{\partial L}{\partial W^{(2)}} = h^T (p - y)
$$

$$
\frac{\partial L}{\partial b^{(2)}} = p - y
$$

---

## ステップ③：隠れ層への伝播

$$
\frac{\partial L}{\partial h} = (p - y) {W^{(2)}}^T
$$

---

## ステップ④：ReLUの勾配

ReLU：
$$
\mathrm{ReLU}(x) = \max(0, x)
$$

微分：

$$
\frac{d}{dx} \mathrm{ReLU}(x) =
\begin{cases}
1 & (x > 0) \\
0 & (x \leq 0)
\end{cases}
$$

---

$$
\frac{\partial L}{\partial z^{(1)}} =
\frac{\partial L}{\partial h} \odot \mathrm{ReLU}'(z^{(1)})
$$

---

## ステップ⑤：第1層の勾配

$$
\frac{\partial L}{\partial W^{(1)}} = x^T \frac{\partial L}{\partial z^{(1)}}
$$

$$
\frac{\partial L}{\partial b^{(1)}} = \frac{\partial L}{\partial z^{(1)}}
$$

---

## まとめ

$$
\frac{\partial L}{\partial z^{(2)}} = p - y
$$

$$
\frac{\partial L}{\partial W^{(2)}} = h^T (p - y)
$$

$$
\frac{\partial L}{\partial W^{(1)}} = x^T \left[ ((p - y) {W^{(2)}}^T) \odot \mathrm{ReLU}'(z^{(1)}) \right]
$$

---

## 直感

- 出力層：誤差 = p - y
- 隠れ層：誤差を逆伝播して調整
- 活性化関数：情報を通す or 止める

---

## 本質

勾配は後ろから前に流れる：

$$
L \leftarrow p \leftarrow z^{(2)} \leftarrow h \leftarrow z^{(1)} \leftarrow x
$$

---

## ポイント

- 誤差は後ろから伝わる
- 各層で「入力 × 誤差」の形になる
- 活性化関数が勾配の流れを制御する

##コード例

In [23]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(float)

def softmax(x):
    x = x - np.max(x)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def forward(x, W1, b1, W2, b2):
    z1 = x @ W1 + b1
    h = relu(z1)
    z2 = h @ W2 + b2
    p = softmax(z2)
    return z1, h, z2, p

def backward(x, y, z1, h, z2, p, W2):
    dz2 = p - y

    dW2 = np.outer(h, dz2)
    db2 = dz2

    dh = dz2 @ W2.T
    dz1 = dh * relu_grad(z1)

    dW1 = np.outer(x, dz1)
    db1 = dz1

    return dW1, db1, dW2, db2

# 多層ニューラルネット（3層以上）の一般化

## モデル（L層）

入力：
$$
a^{(0)} = x
$$

各層（l = 1, ..., L）：

$$
z^{(l)} = a^{(l-1)} W^{(l)} + b^{(l)}
$$

$$
a^{(l)} = f^{(l)}(z^{(l)})
$$

出力層（softmax）：
$$
a^{(L)} = p
$$

---

## 全体の流れ

$$
x \rightarrow z^{(1)} \rightarrow a^{(1)} \rightarrow z^{(2)} \rightarrow \cdots \rightarrow z^{(L)} \rightarrow p \rightarrow L
$$

---

## ステップ①：出力層

$$
\delta^{(L)} = \frac{\partial L}{\partial z^{(L)}} = p - y
$$

---

## ステップ②：逆伝播（一般形）

各層について：

$$
\delta^{(l)} =
\left( \delta^{(l+1)} {W^{(l+1)}}^T \right)
\odot f'(z^{(l)})
$$

---

## ステップ③：勾配

$$
\frac{\partial L}{\partial W^{(l)}} =
{a^{(l-1)}}^T \delta^{(l)}
$$

$$
\frac{\partial L}{\partial b^{(l)}} =
\delta^{(l)}
$$

---

## まとめ（最重要）

$$
\delta^{(L)} = p - y
$$

$$
\delta^{(l)} = (\delta^{(l+1)} W^{(l+1)T}) \odot f'(z^{(l)})
$$

$$
\frac{\partial L}{\partial W^{(l)}} = a^{(l-1)T} \delta^{(l)}
$$

---

## 直感

- 誤差は後ろから前に伝わる
- 各層で「入力 × 誤差」で重み更新
- 活性化関数が勾配の流れを制御

---

## 本質

バックプロパゲーションとは：

$$
誤差をチェーンルールで逆方向に伝えるだけ
$$

---

## 図イメージ

$$
L \leftarrow a^{(L)} \leftarrow z^{(L)} \leftarrow \cdots \leftarrow z^{(1)} \leftarrow x
$$

---

## ポイント

- どれだけ層が増えても同じ式
- 「δ（デルタ）」を伝播するだけ
- 計算はすべて行列演算で書ける

##コード例

In [24]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(float)

def softmax(x):
    x = x - np.max(x)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

# forward
def forward(x, weights, biases):
    """
    weights: list of W
    biases: list of b
    """
    activations = [x]
    zs = []

    a = x
    for i in range(len(weights) - 1):
        z = a @ weights[i] + biases[i]
        zs.append(z)
        a = relu(z)
        activations.append(a)

    # 最後はsoftmax
    z = a @ weights[-1] + biases[-1]
    zs.append(z)
    a = softmax(z)
    activations.append(a)

    return activations, zs


# backward
def backward(x, y, weights, biases, activations, zs):
    L = len(weights)

    dWs = [None] * L
    dbs = [None] * L

    # 出力層
    delta = activations[-1] - y

    for l in reversed(range(L)):
        a_prev = activations[l]

        dWs[l] = np.outer(a_prev, delta)
        dbs[l] = delta

        if l > 0:
            delta = (delta @ weights[l].T) * relu_grad(zs[l-1])

    return dWs, dbs

# 勾配消失問題（Vanishing Gradient）

## 現象

ネットワークが深くなると、前の層に勾配がほとんど届かなくなる：

$$
\frac{\partial L}{\partial W^{(1)}} \approx 0
$$

→ 重みが更新されない → 学習が進まない

---

## 原因（チェーンルールの連続）

バックプロパゲーションでは：

$$
\delta^{(l)} =
\left( \delta^{(l+1)} W^{(l+1)T} \right)
\odot f'(z^{(l)})
$$

これを展開すると：

$$
\delta^{(1)} =
\delta^{(L)} \cdot
\prod_{k=2}^{L} \left( W^{(k)} f'(z^{(k-1)}) \right)
$$

---

## 何が起きているか

- 多数の「小さい値」を掛け続ける
- 結果として指数的に小さくなる

$$
0.5 \times 0.5 \times 0.5 \times \cdots \rightarrow 0
$$

---

## sigmoid の問題

sigmoid：

$$
\sigma(x) = \frac{1}{1 + e^{-x}}
$$

導関数：

$$
\sigma'(x) = \sigma(x)(1 - \sigma(x)) \le 0.25
$$

---

## 結論

各層で最大でも 0.25 倍：

$$
(0.25)^L \rightarrow 0
$$

層が深くなると：

$$
\delta \rightarrow 0
$$

---

## 直感

- 誤差が後ろから伝わる
- 途中でどんどん弱くなる
- 最初の層まで届かない

---

## 何が問題か

- 初期層が学習されない
- 特徴抽出ができない
- モデルが賢くならない

---

## 解決策

### 1. ReLU

$$
f'(x) =
\begin{cases}
1 & (x > 0) \\
0 & (x \le 0)
\end{cases}
$$

→ 勾配が減衰しにくい

---

### 2. 重み初期化（He初期化）

→ 分散を保つ

---

### 3. Batch Normalization

→ 分布を安定化

---

### 4. Residual Connection（ResNet）

$$
y = f(x) + x
$$

→ 勾配が直接流れる

---

## 本質

勾配消失とは：

$$
小さい値の連続積による指数的減衰
$$

##コード例

In [25]:
import numpy as np

# sigmoidの微分
def sigmoid_grad(x):
    s = 1 / (1 + np.exp(-x))
    return s * (1 - s)

# 勾配の減衰をシミュレーション
layers = 20
grad = 1.0

print("layer  grad")

for i in range(layers):
    g = sigmoid_grad(np.random.randn())
    grad *= g
    print(f"{i+1:2d}    {grad:.10f}")

layer  grad
 1    0.1255992271
 2    0.0307063742
 3    0.0076761076
 4    0.0013354580
 5    0.0003168937
 6    0.0000470277
 7    0.0000111963
 8    0.0000027926
 9    0.0000006523
10    0.0000001283
11    0.0000000278
12    0.0000000043
13    0.0000000010
14    0.0000000001
15    0.0000000000
16    0.0000000000
17    0.0000000000
18    0.0000000000
19    0.0000000000
20    0.0000000000


In [27]:
def relu_grad(x):
    return np.where(x > 0, 1.0, 0.0)

grad = 1.0

for i in range(20):
    g = relu_grad(np.random.randn())
    grad *= g
    print(grad)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
