<a href="https://colab.research.google.com/github/kyoseikamada/machinelearning/blob/main/neural-network1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ライブラリのimport

In [1]:
import numpy as np

# NumPy 基本まとめ

##1. 配列の作成

In [7]:
# 1次元配列（ベクトル）
a = np.array([1, 2, 3])
print("a:", a)

a: [1 2 3]


In [9]:
# 2次元配列（行列）
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("b:\n", b)

b:
 [[1 2 3]
 [4 5 6]]


In [10]:
# 指定サイズで初期化
zeros = np.zeros((2, 3))   # 2行3列、すべて0
ones = np.ones((2, 3))     # 2行3列、すべて1
print("zeros:\n", zeros)
print("ones:\n", ones)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# 連続値の生成
ar = np.arange(0, 10, 2)   # 0〜10未満、2刻み
ls = np.linspace(0, 1, 5)  # 0〜1を5分割
print("arange:", ar)
print("linspace:", ls)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 2. shape と dtype

In [12]:
# shape = (行, 列)
print("b.shape:", b.shape)

# dtype = データ型
print("b.dtype:", b.dtype)

b.shape: (2, 3)
b.dtype: int64


## 3. インデックス / スライス


In [13]:
# 要素アクセス（行, 列）
print("b[0,1]:", b[0, 1])  # 1行目2列目

# 行の取得
print("b[0]:", b[0])       # 1行目

# 列の取得
print("b[:,1]:", b[:, 1])  # 2列目

# 部分行列（スライス）
print("b[0:2,1:3]:\n", b[0:2, 1:3])


b[0,1]: 2
b[0]: [1 2 3]
b[:,1]: [2 5]
b[0:2,1:3]:
 [[2 3]
 [5 6]]


## 4. 要素ごとの演算（超重要）

In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 同じshape同士は要素ごとに計算される
print("x + y:", x + y)
print("x * y:", x * y)
print("x ** 2:", x ** 2)


x + y: [5 7 9]
x * y: [ 4 10 18]
x ** 2: [1 4 9]


## 5. ブロードキャスト（超重要）

In [17]:

# (2,3) + (3,) の計算
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# xが各行に自動で拡張される
print("m + x:\n", m + x)

m + x:
 [[2 4 6]
 [5 7 9]]


## 6. 行列演算（要素演算と違う）

In [18]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 要素ごとの掛け算
print("A * B:\n", A * B)

# 行列積（線形代数）
print("A @ B:\n", A @ B)

A * B:
 [[ 5 12]
 [21 32]]
A @ B:
 [[19 22]
 [43 50]]


## 7. 統計処理

In [19]:
data = np.array([1, 2, 3, 4, 5])

print("sum:", np.sum(data))
print("mean:", np.mean(data))
print("max:", np.max(data))
print("min:", np.min(data))

sum: 15
mean: 3.0
max: 5
min: 1



##8. reshape（形の変更）


In [20]:
r = np.arange(6)
print("before:", r)

# (6,) → (2,3)
r2 = r.reshape(2, 3)
print("after:\n", r2)

before: [0 1 2 3 4 5]
after:
 [[0 1 2]
 [3 4 5]]


## 9. 条件抽出（フィルタ）


In [21]:
a = np.array([1, 2, 3, 4, 5])

# 条件（True/False配列）
mask = a > 3
print("mask:", mask)

# 条件に合う要素だけ取り出す
print("filtered:", a[mask])

mask: [False False False  True  True]
filtered: [4 5]


## 10. グラフ・機械学習でよく使う形

In [22]:

# 入力データ生成
x = np.linspace(-5, 5, 100)

# 関数適用（ベクトル化）
y = x ** 2

print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (100,)
y shape: (100,)


#勾配を求める

In [24]:
def numerical_gradient(f, x):
  """
  Parameters
  ----------
  f : function
      入力: numpy配列
      出力: numpy配列
  x : numpy.ndarray
  """
  h = 1e-4
  grad = np.zeros_like(x)

  for idx in range(x.size):
    tmp_val = x[idx]
    # f(x+h)の計算
    x[idx] = tmp_val + h
    fxh1 = f(x)

    # f(x-h)の計算
    x[idx] = tmp_val - h
    fxh2 = f(x)

    grad[idx] = (fxh1 - fxh2) / (2*h)
    x[idx] = tmp_val

  return grad


In [32]:
def func(x):
  """
  2次元配列(numpy配列)
  """
  return x[0]**2 + x[1]**2

print("例1:", numerical_gradient(func, np.array([3.0, 4.0])))
print("例2:", numerical_gradient(func, np.array([0.0, 2.0])))
print("例3:", numerical_gradient(func, np.array([3.0, 0.0])))

例1: [6. 8.]
例2: [0. 4.]
例3: [6. 0.]


#勾配降下法

In [43]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
  """
  f: function
  init_x: xの初期値
  lr: 学習率
  step_num: 学習回数
  """
  x = init_x

  for i in range(step_num):
    grad = numerical_gradient(f, x)
    x -= lr * grad

  return x

##例）関数の極小値を求める

In [44]:
init_x = np.array([-3.0, 4.0])
x = gradient_descent(func, init_x, lr=0.1, step_num=100)

print(x)

[-6.11110793e-10  8.14814391e-10]


In [45]:
func(x)

np.float64(1.0373788922158197e-18)

funcの極小値は0なので、ほぼ正解に近い値を求められている

ハイパーパラメータの学習率lrを小さい値に設定すると上手くいかない

In [46]:
init_x = np.array([-3.0, 4.0])
x = gradient_descent(func, init_x, lr=0.001, step_num=100)

print("x:", x)
print("func:", func(x))

x: [-2.45570041  3.27426722]
func: 16.75129034343203


#ソフトマックス関数・クロスエントロピー関数

## ソフトマックス関数

$$
\mathrm{softmax}(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{n} e^{x_j}}
$$

数値安定化のための実装では、以下を用いる：

$$
\mathrm{softmax}(x_i) = \frac{e^{x_i - \max(x)}}{\sum_{j=1}^{n} e^{x_j - \max(x)}}
$$



In [47]:
import numpy as np

def softmax(x):
    """
    x: numpy.ndarray (n,) または (batch, n)
    return: softmax適用結果（同じshape）
    """
    # 数値安定化（オーバーフロー防止）
    x = x - np.max(x, axis=-1, keepdims=True)

    exp_x = np.exp(x)
    sum_exp = np.sum(exp_x, axis=-1, keepdims=True)

    return exp_x / sum_exp

## クロスエントロピー損失関数

分類問題におけるクロスエントロピー：

$$
L = - \sum_{i=1}^{n} y_i \log p_i
$$

ここで：

- $y_i$：正解ラベル（one-hotベクトル）
- $p_i$：予測確率（softmaxの出力）

---

バッチデータの場合：

$$
L = - \frac{1}{N} \sum_{k=1}^{N} \sum_{i=1}^{n} y_{k,i} \log p_{k,i}
$$

In [48]:
import numpy as np

def cross_entropy(y_true, y_pred):
    """
    y_true: (n,) または (batch, n) one-hot
    y_pred: (n,) または (batch, n) softmax出力

    return: スカラー損失
    """
    # log(0)防止
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)

    return -np.sum(y_true * np.log(y_pred)) / y_true.shape[0]